---
- project:
    queue: kayobe
    check:
      jobs:
        - openstack-tox-pep8
        - kayobe-overcloud-rocky9
        - kayobe-overcloud-centos9s
        - kayobe-overcloud-ubuntu-noble
        - kayobe-overcloud-tls-rocky9
        - kayobe-overcloud-host-configure-rocky9
        - kayobe-overcloud-host-configure-centos9s
        - kayobe-overcloud-host-configure-ubuntu-noble
        - kayobe-overcloud-upgrade-rocky9
        - kayobe-overcloud-upgrade-ubuntu-jammy
        - kayobe-seed-rocky9
        - kayobe-seed-ubuntu-noble
        - kayobe-seed-images-rocky9
        - kayobe-seed-upgrade-rocky9
        - kayobe-seed-upgrade-ubuntu-jammy
        - kayobe-seed-vm-rocky9
        - kayobe-seed-vm-rocky9-efi
        - kayobe-seed-vm-ubuntu-noble
        - kayobe-seed-vm-ubuntu-noble-efi
        - kayobe-infra-vm-rocky9
        - kayobe-infra-vm-ubuntu-noble
    gate:
      jobs:
        - openstack-tox-pep8
        - kayobe-overcloud-rocky9
        - kayobe-overcloud-ubuntu-noble
        - kayobe-overcloud-tls-rocky9
        - kayobe-overcloud-host-configure-rocky9
        - kayobe-overcloud-host-configure-ubuntu-noble
        - kayobe-overcloud-upgrade-rocky9
        - kayobe-overcloud-upgrade-ubuntu-jammy
        - kayobe-seed-rocky9
        - kayobe-seed-ubuntu-noble
        - kayobe-seed-upgrade-rocky9
        - kayobe-seed-upgrade-ubuntu-jammy
        - kayobe-seed-vm-rocky9
        - kayobe-seed-vm-ubuntu-noble
        - kayobe-infra-vm-rocky9
        - kayobe-infra-vm-ubuntu-noble
