---
- project:
    queue: kayobe
    check:
      jobs:
        - openstack-tox-pep8
        - kayobe-overcloud-centos
        - kayobe-seed-centos

    gate:
      jobs:
        - openstack-tox-pep8
        - kayobe-overcloud-centos
        - kayobe-seed-centos